### ISSUE TITLE
Improve tree-shaking by import data models separately

### ISSUE THREAD

**Issue by nicholaschiang** [tutorbookapp/tutorbook#157]
Oh, another performance fix you guys could help out with is improving the tree shaking for our `lib/model` data models.

Right now, they're all being imported from the `lib/model` file which prevents code-splitting the different data models:

```typescript
import { User, UsersQuery, Availability, Meeting, Match } from 'lib/model';
```

Instead, they should all be imported separately from their individual files, like so:

```typescript
import { User } from 'lib/model/user';
import { UsersQuery } from 'lib/model/query/users';
import { Availability } from 'lib/model/availability';
import { Meeting } from 'lib/model/meeting';
import { Match } from 'lib/model/match';
```

You should just search the code-base for imports of `lib/model` and then break them up like that. Once you've finished, then just remove the `lib/model/index.ts` file and try to compile. If it succeeds without any import errors, then create a PR!

**Comment by avoajaugochukwu** [comment]
I have started working on this.
