### ISSUE TITLE
fix: add i18n to grade levels

### ISSUE THREAD

**Issue by ChristopherWong274** [tutorbookapp/tutorbook#44]
hey guys, we need to add a grading to all the courses like for example, we could put 'senior/grade 12' instead of just senior. Like this students from diff countries can have a better understanding of the system.

**Comment by RashmitShrestha** [comment]
Actually I think just doing something like "9th grade, 10th grade, etc" so that it'll be parallel to the other grades in middle school and down. What do you guys think? - (Get rid of freshman, sophmore, etc. completely?)

**Comment by nicholaschiang** [comment]
@RashmitShrestha and @ChristopherWong274 we'll adjust the grade levels and the subjects shown based on the user's locale.

@ChristopherWong274 what is your country's locale code (e.g. the United States' is `en-US`)? What are the grade levels and subjects for your country?

@RashmitShrestha I'll update the "Freshman, Sophomore" in the English-US locale to be "9th Grade, 10th Grade" for now as well.

**Comment by nicholaschiang** [comment]
We'll need to add support for the Mauritius locale (that's where @ChristopherWong274 is based).

**Comment by nicholaschiang** [comment]
See #35 for more info on how we do i18n.

**Comment by nicholaschiang** [comment]
Closing this because we no longer collect grade level (due to changes in the `SubjectSelect`; see #20).

**Comment by ChristopherWong274** [comment]
sorry for the late reply; our country local code is en-UK. We use the same system as British
