### ISSUE TITLE
Add custom error page

### ISSUE THREAD

**Issue by nicholaschiang** [tutorbookapp/tutorbook#47]
Read [the Next.js documentation on custom error pages](https://nextjs.org/docs/advanced-features/custom-error-page) and implement our own custom error page using the styling from the rest of the site (e.g. use `@rmwc/typography`, perhaps a nice background image from [our web assets](https://assets.tutorbook.org/), etc).

Note that this error page should have as little text as possible (because it has to be static and thus we can't use `react-intl` for i18n). Or just include the error message in all of our supported locales (see the list in `src/intl/config.json`).

**Comment by vamsikrishnareddybevara** [comment]
@nicholaschiang , I would like to solve this issue.

**Comment by nicholaschiang** [comment]
@vamsikrishnareddybevara I'm just seeing this! I'd love to have you help out with this. I'm guessing we'll want to create something similar to [Vercel's custom 404 page](https://vercel.com/asfasdfa) that includes our nav bar and links to recommended destinations.

Also, we should update the current `<ErrorPage />` usage in the restricted `pages/[org]` routes to instead redirect to a custom 404 page (like Vercel does when users are unauthenticated) or to a prompt to login with another account that does have access to those orgs.
