### ISSUE TITLE
feat: social icons instead of plain links

### ISSUE THREAD

**Issue by nicholaschiang** [tutorbookapp/tutorbook#48]
Right now, the `UserDialog` displays plain text links for the user's social media accounts like so:

![image](https://user-images.githubusercontent.com/20798889/81884013-9b5ef980-954b-11ea-924a-2107f3465b4a.png)

Ideally, we want them to be easily recognizable yet still discreet social media icons (probably all in gray and pretty small).

Consult with our design team (e.g. @kryssym) to review your work once you're finished.

**Comment by kryssym** [comment]
Did you want a stylized set of icons or icons straight from those sites? I don't make icons..... Otherwise we can download them directly from their brand guidelines pages.

**Comment by nicholaschiang** [comment]
I addressed this in the new redesign using Font Awesome icons.
