### ISSUE TITLE
Polish timeslot input behavior and design

### ISSUE THREAD

**Issue by nicholaschiang** [tutorbookapp/tutorbook#49]
**The problem**
Our existing timeslot input is rather painful (i.e. as a user you have to read the helper text carefully to see what timeslots are available for selection) and is text-based (which makes i18n hard and forces the user to type out "Mondays from 3:00 PM to 3:30 PM").

![image](https://user-images.githubusercontent.com/20798889/81884144-eda01a80-954b-11ea-9f98-96ef30a5e9fd.png)

**The solution**
Just posted to the **#team-design** Slack channel with this, so hopefully we'll have a solution designed soon:
> Hey **@channel** could you help design a timeslot input that will:
> 1. Replace the text-based one in the UserDialog (see above picture).
> 2. Select a timeslot (e.g. "Mondays from 3:00 PM to 3:30 PM") from a given availability.

**Comment by kryssym** [comment]
For tutor availability I think we can emulate calendly. Having the dates and times available highlighted is an easier visual cue.

![image](https://user-images.githubusercontent.com/64979981/81974272-30103880-95da-11ea-9fd7-4bd87d0b0dc4.png)

**Comment by kryssym** [comment]
Is there a max amount of time a student can book with one tutor?

**Comment by nicholaschiang** [comment]
Nope @kryssym there isn't (right now). A student can book a tutor for as much time as they want to as many times as they want.

I'm guessing we should probably change that haha.. I just opened #59 to address it.

**Comment by kryssym** [comment]
![time_slot_input_V1](https://user-images.githubusercontent.com/64979981/83076463-70d06e80-a02a-11ea-9727-377536528896.png)
I made a mockup of have the time slots in 30 minute increments. This is just expanding the tutor profile card in the search results.
