### ISSUE TITLE
Polish availability input's specificity

### ISSUE THREAD

**Issue by nicholaschiang** [tutorbookapp/tutorbook#50]
**The problem**
Our existing availability input constrains the user to 3-hr blocks of time and can be rather time-consuming to check (or uncheck after a "Select all" click) each box.

![image](https://user-images.githubusercontent.com/20798889/81884468-df063300-954c-11ea-9507-3c4d3126768e.png)

**The solution**
We'll need an input that will:
- Replace the checkbox-based one pictured above.
- Allow for more specificity (i.e. users aren't constrained to set 3-hour blocks). For example, I should be able to say that I'm free from 12:30 PM to 1:46 PM on Monday.
- Emulate the week view on Google Calendar.
- Have an option to sync with iCal or Google Calendar (e.g. I import my existing calendar items and any time that isn't already "busy" is added as availability).

I already pinged our design team on this, hopefully they'll have a solution designed that we can then implement soon.

**Comment by kryssym** [comment]
Allowing the time to be specific to the minute will make the experience much slower. It's commonly found practice to break into 30 minute slots–15 min slots at most.

Drag to select an allotted timeframe on a calendar layout between 7am–10pm

**Comment by nicholaschiang** [comment]
We'll want to implement something like Google Calendar's drag-to-resize/position event creation UX (except that we'll show the user a weekly view so they can edit their availability for the whole week in one place):

![drag-to-resize](https://user-images.githubusercontent.com/20798889/87564806-af22fb00-c675-11ea-89d9-6877f2d3e384.gif)

To do this, we'll probably want to look into a React library like [`react-rnd`](https://github.com/bokuweb/react-rnd) which will handle all of the drag resizing and positioning for us. Then, all we'll have to do is build the week view UI and event listeners to update the user's availability whenever a schedule item is resized or re-positioned.
