### ISSUE TITLE
[RFC] Add org "people" dashboard and partitioned vetting

### ISSUE THREAD

**Issue by nicholaschiang** [tutorbookapp/tutorbook#75]
**Is your feature request related to a problem? Please describe.**

Our software will be used by nonprofit organizations to manage their free tutoring and mentoring initiatives. There are many existing orgs that do essentially exactly what we're doing, just at a smaller scale and without a dedicated software solution.

Most of those nonprofits are using Google Forms paired with Google Sheets, Gmail, and a third-party video conferencing solution (i.e. for the virtual tutoring/mentoring). While this approach works, it requires much manual labor (and thus isn't scalable), a bad user experience for the tutors, mentors, and students involved, and isn't trackable (i.e. there isn't an easy way to record all those virtual tutoring sessions when they're going through a third-party vendor).

**Describe the solution you'd like**

Nonprofits (e.g. [Project Access](https://projectaccess.org), [StudyRoom](https://studyroom.at), [CTI](https://coronavirustutoring.co.uk), [Big Brothers Big Sisters](https://bbbs.org)) will use our software to:
1. **Streamline the sign-up and vetting process for new tutors/mentors.**
  a. The tutor/mentor will sign-up (at an org-specific link) using Tutorbook's awesome UI.
  b. Because the tutor/mentor signed up using that org-specific link, their profile will appear in the org's "people" dashboard as a "pending sign-up" (i.e. yet to be verified).
  c. The org will then run their verification process (e.g. checking the sign-ups LinkedIn, Facebook) and adds a note to the tutor's/mentor's profile saying "We've done X, Y, and Z to ensure that this person is who they say they are" (perhaps this will also make the org liable if the tutor/mentor does anything wrong).
  d. Once verified, the tutor/mentor will appear in search results.
2. **Track and record virtual tutoring/mentoring sessions.**
  a. We'll have a built-in video conferencing and chat solutions (i.e. essentially re-building Slack).
  b. All communications and tutoring sessions will be recorded and accessible to the org.
  c. Unlike existing third-party video calling solutions, Tutorbook won't send spam to their users.
3. **Access the huge, shared pool of tutors and mentors on Tutorbook.**
  a. All tutor/mentor sign-ups (no matter what org they signed up through) get placed into the central pool of tutors.
  b. Anyone can search everyone else's tutors/mentors, but most likely they'll only be searching their own tutors/mentors (because the search view prefers tutors/mentors that are closest to you... see #74).
  c. Consumers (i.e. students or their parents) will be able to access that shared pool of tutors/mentors directly via Tutorbook's web app.

**Additional context**

This is similar to what @lazyplatypus is doing with @bitprj. It's a distributed model where all the smaller nonprofits engage their own "micro-communities" to get tutors/mentors and match them with the students (in their "micro-communities") who need them the most. Those orgs do all the outreach work for us; we merely provide a scalable software solution to make their work faster and more efficient.

@kryssym and @ryantzr1 I'd love to get your design input on this system. Is there anything that stands out to you that could go wrong?

**Comment by nicholaschiang** [comment]
Just added [this documentation](https://github.com/tutorbookapp/tutorbook/tree/develop/src/model#readme) which specifies what our data models and data flow will look like.

**Comment by Akanchatandon** [comment]
Here are some key features that I have put together as User stories.
[Tutor Book Stories.xlsx](https://github.com/tutorbookapp/tutorbook/files/4782764/Tutor.Book.Stories.xlsx)

**Comment by Akanchatandon** [comment]
Each feature outlined in the doc will define its own userflow that will connect the stories across Tutorbook application.

**Comment by nicholaschiang** [comment]
I'm going to add this under the `0.9.0` milestone, but we're (most likely) going to leave out the in-app video conferencing feature for now. Instead, we'll focus on just the search view and the initial connection (i.e. a huge repository of a bunch of awesome tutors and mentors; the Craigslist of tutoring and mentoring).

That means (among other things):
- Fixing the scrolling issues (we're using `react-window`) and pagination on the current "People" dashboard.
- Fixing the `VerificationDialog` state management (right now, it's being controlled by the "People" dashboard's `useSWR` hook but that takes too long to re-render).
- Polishing the partitioned search (i.e. the org filters where you only see results from a certain org).
- Adding vanity URLs for organizations (e.g. `https://tutorbook.org/projectaccess/search`).

Some ideas (that might or might not make it into `0.9.0` by the end of this week):
- Custom descriptions in the org-specific sign-up page.
- Statistics dashboard showing new sign-ups, requests, etc.
- Way to view all communications (sent via the email relay solution described in #82) and requests of org users.
- Easy integration with vetting services (i.e. the organization can pay to run background checks on their new sign-ups).

**Comment by nicholaschiang** [comment]
Closing this temporarily because we've implemented the MVP that was described in the last comment and released it in `0.9.0`; we're not going to be coming back to this issue anymore anyways (we'll create smaller task-based issues that contribute to the ideas behind this high-level RFC instead).
