### ISSUE TITLE
Add dark mode

### ISSUE THREAD

**Issue by geekyahmed** [tutorbookapp/tutorbook#79]
**Is your feature request related to a problem? Please describe.**
This is actually a great way to hell users have a much better experience using dark mode especially for people who don't like the exposure of light.

**Describe the solution you'd like**
Since it is based on Nexjsand react, a couple of components are out there that you can be able to integrate to make it seamless and easy to use.

**Describe alternatives you've considered**
None actually

**Comment by nicholaschiang** [comment]
Thanks @geekyahmed (PRs are always welcome too, if you want to have a stab at implementing this yourself)!

We'll have to change our `config.$colors` Sass variable (defined in [`src/styles/config.scss`](https://github.com/tutorbookapp/tutorbook/blob/develop/src/styles/config.scss#L18)) to be global CSS variables that are toggled by the dark/light mode toggle @geekyahmed was referring to (this is what [Vercel's website](https://vercel.com) does right now).

We'll want to follow [the Material Design spec](https://material.io/design/color/dark-theme.html) for dark theming as well (e.g. the Vercel dark theme has too much contrast IMO).

**Comment by geekyahmed** [comment]
Sure I will
